# Generated by Django 6.1.1 on 2026-09-23 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Ex: fisio, catalogo, petshop, loja_livros - SEM espaço', unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ASSINATURA', 'Assinatura - Cobra mensalidade'), ('VENDA', 'Venda - Só recebe comissão')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Ex: mensal, trimestral, anual')),
                ('nome', models.CharField(help_text='Ex: Plano Mensal - R$49', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ciclo', models.CharField(choices=[('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral (3 meses)'), ('SEMIANNUALLY', 'Semestral (6 meses)'), ('YEARLY', 'Anual (12 meses)'), ('WEEKLY', 'Semanal')], default='MONTHLY', max_length=20)),
                ('dias_trial', models.IntegerField(default=7, help_text='0 = sem trial')),
                ('ativo', models.BooleanField(default=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.sistema')),
            ],
            options={
                'unique_together': {('sistema', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=100)),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('trial', 'Em Trial'), ('ativa', 'Ativa'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada'), ('inativa', 'Inativa')], default='trial', max_length=20)),
                ('inicio_em', models.DateTimeField(auto_now_add=True)),
                ('trial_fim', models.DateField(blank=True, null=True)),
                ('proximo_vencimento', models.DateField(blank=True, null=True)),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plano')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email_comprador', models.EmailField(blank=True, max_length=254)),
                ('dados_extras', models.JSONField(blank=True, default=dict, help_text='Guarda JSON que veio da loja')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sistema', models.ForeignKey(help_text='Só sistemas tipo VENDA', on_delete=django.db.models.deletion.CASCADE, to='core.sistema')),
            ],
        ),
    ]
