# Generated by Django 6.1.1 on 2026-09-24 16:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='token',
            field=models.CharField(default=core.models.gerar_token, help_text='Token que este sistema usa para chamar a central', max_length=64, unique=True),
        ),
    ]
