# Generated by Django 6.1.1 on 2026-09-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sistema_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição exibida na página de planos do sistema'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='notificar_url',
            field=models.URLField(blank=True, help_text='URL do sistema que a central avisa quando o status da assinatura muda (opcional)'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='evento_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sistema'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='tipo',
            field=models.CharField(blank=True, help_text='Ex: asaas:PAYMENT_CONFIRMED, evento:EVENTO_CRIADO', max_length=100),
        ),
    ]
