# Generated by Django 6.1.1 on 2026-09-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plano_descricao_sistema_notificar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='ciclo_asaas',
            field=models.CharField(blank=True, default='MONTHLY', max_length=20),
        ),
    ]
