# Generated by Django 6.1.1 on 2026-09-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assinatura_ciclo_asaas'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='referencia',
            field=models.CharField(blank=True, help_text='Chave externa do objeto no sistema (ex: listing:12)', max_length=200),
        ),
    ]
